### ISSUE TITLE
MH-Z19B measures well the first 15 minutes, then 0 ppm

### ISSUE THREAD

**Issue by Osfuco** [WifWaf/MH-Z19#48]
Good afternoon, I have an MH-Z19B connected to an ESP12, when I connect it to the power supply it works fine for the first 15 minutes, then it stops measuring 0 ppm. Does anyone know how to fix it?

**Comment by WifWaf** [comment]
Have you tried manually calibrating the sensor? It might be due to the sensor lacking any reference values.

Outside of this, the only time it's happened to me is when I corrupted the firmware, but it took quite some effort.

**Comment by Osfuco** [comment]
The sensor is calibrated. In fact, for the first few minutes it works perfectly, but then it dies (the light keeps flashing but it sends 0ppm).

There are 3 sensors. Maybe they are defective?

**Comment by Osfuco** [comment]
I have a 4th sensor model MH-Z19C with the same code and works perfectly all the time (15 days)

**Comment by WifWaf** [comment]
Is the issue with all 3 sensors?

If the library filter is on, it might be worth turning it off and seeing if it zeros or just erroneous data.

As a last resort, you could try setting the range to 2000 (if that's the CO2 limit you using), although it might make things worse.  I can't remember the reason, however, I've had to do with this with a sensor before. Unfortunately, it's been a while since I used the sensor.

**Comment by WifWaf** [comment]
Closing for now due inactivity, feel free to reopen.
